[package]
name = "tuzuku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.1.5"
chumsky = "0.8.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.13.0"
typed-arena = "2.0.1"
